"""add subresponse id + integration with response - prob. works

Revision ID: 440f2192662f
Revises: 
Create Date: 2018-10-13 08:39:24.870186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440f2192662f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_content'), 'post', ['content'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_index(op.f('ix_post_topics'), 'post', ['topics'], unique=False)
    op.add_column('responses', sa.Column('opt_subresponse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_responses_timestamp'), 'responses', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'responses', 'responses', ['opt_subresponse_id'], ['id'])
    op.create_index(op.f('ix_users_about'), 'users', ['about'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=True)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=True)
    op.create_index(op.f('ix_users_password_hashed'), 'users', ['password_hashed'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password_hashed'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_about'), table_name='users')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_index(op.f('ix_responses_timestamp'), table_name='responses')
    op.drop_column('responses', 'opt_subresponse_id')
    op.drop_index(op.f('ix_post_topics'), table_name='post')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_content'), table_name='post')
    # ### end Alembic commands ###
