FLASK_APP=flim.py
FLASK_DEBUG=1

FLIM_DB_NAME=flim
FLIM_DB_HOST=localhost
FLIM_DB_PORT=3306
FLIM_DB_PROVIDER=mysql
FLIM_DB_USERNAME=default_u
FLIM_DB_PASSWORD=letmeinmysql
FLIM_HOST=0.0.0.0
FLIM_PORT=5000
FLIM_ALLOW_REGISTRATION=0
